-- KAALIX progression schema for MySQL/PostgreSQL style databases.
-- The app runs with Hibernate auto-update locally; use this as the production schema guide.

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    user_key VARCHAR(255) NOT NULL UNIQUE,
    level INTEGER NOT NULL DEFAULT 1,
    txp INTEGER NOT NULL DEFAULT 0,
    total_txp INTEGER NOT NULL DEFAULT 0,
    daily_txp INTEGER NOT NULL DEFAULT 0,
    next_level_xp INTEGER NOT NULL DEFAULT 127,
    rank VARCHAR(32) NOT NULL DEFAULT 'E',
    streak INTEGER NOT NULL DEFAULT 0,
    last_active_date DATE,
    initial_rank_locked BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS daily_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    date DATE NOT NULL,
    study_hours DOUBLE PRECISION NOT NULL DEFAULT 0,
    dsa_count INTEGER NOT NULL DEFAULT 0,
    workout BOOLEAN NOT NULL DEFAULT FALSE,
    wake_on_time BOOLEAN NOT NULL DEFAULT FALSE,
    no_distractions BOOLEAN NOT NULL DEFAULT FALSE,
    skip_study BOOLEAN NOT NULL DEFAULT FALSE,
    late_wake BOOLEAN NOT NULL DEFAULT FALSE,
    overthinking_anger BOOLEAN NOT NULL DEFAULT FALSE,
    wasted_time DOUBLE PRECISION NOT NULL DEFAULT 0,
    tasks_completed INTEGER NOT NULL DEFAULT 0,
    total_tasks INTEGER NOT NULL DEFAULT 0,
    score INTEGER NOT NULL DEFAULT 0,
    txp_earned INTEGER NOT NULL DEFAULT 0,
    daily_txp INTEGER NOT NULL DEFAULT 0,
    actions_data TEXT
);

CREATE INDEX IF NOT EXISTS idx_daily_logs_user_date ON daily_logs(user_id, date);

CREATE TABLE IF NOT EXISTS tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    title VARCHAR(255) NOT NULL,
    category VARCHAR(120),
    priority VARCHAR(32) NOT NULL DEFAULT 'MEDIUM',
    scheduled_time VARCHAR(16),
    status VARCHAR(32) NOT NULL DEFAULT 'pending',
    txp_reward INTEGER NOT NULL DEFAULT 20,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS user_stats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE REFERENCES users(id),
    strength INTEGER NOT NULL DEFAULT 0,
    intelligence INTEGER NOT NULL DEFAULT 0,
    discipline INTEGER NOT NULL DEFAULT 0,
    focus INTEGER NOT NULL DEFAULT 0,
    emotional_control INTEGER NOT NULL DEFAULT 0,
    social INTEGER NOT NULL DEFAULT 0,
    style INTEGER NOT NULL DEFAULT 0,
    energy INTEGER NOT NULL DEFAULT 100,
    hp INTEGER NOT NULL DEFAULT 100
);

CREATE TABLE IF NOT EXISTS notes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    category VARCHAR(80) NOT NULL DEFAULT 'Reflection',
    note_text TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS songs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    artist VARCHAR(255),
    source VARCHAR(32) NOT NULL,
    source_url VARCHAR(1024),
    file_path VARCHAR(1024),
    stream_url VARCHAR(1024),
    duration VARCHAR(32),
    cover_image VARCHAR(1024),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS playlists (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    type VARCHAR(64) NOT NULL DEFAULT 'SYSTEM',
    mood VARCHAR(255),
    created_by VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS playlist_songs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    playlist_id BIGINT NOT NULL REFERENCES playlists(id),
    song_id BIGINT NOT NULL REFERENCES songs(id),
    added_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS user_music_preferences (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_key VARCHAR(255) NOT NULL UNIQUE,
    music_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    volume DOUBLE PRECISION NOT NULL DEFAULT 0.35,
    repeat_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    shuffle_enabled BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS connected_music_sources (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_key VARCHAR(255) NOT NULL,
    source VARCHAR(32) NOT NULL,
    connected BOOLEAN NOT NULL DEFAULT FALSE,
    status_message VARCHAR(512),
    connected_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_playlist_songs_playlist ON playlist_songs(playlist_id);
CREATE INDEX IF NOT EXISTS idx_connected_music_sources_user ON connected_music_sources(user_key);

CREATE TABLE IF NOT EXISTS wardrobe_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    category VARCHAR(80) NOT NULL,
    sub_category VARCHAR(120),
    color VARCHAR(80),
    occasion VARCHAR(120),
    season VARCHAR(80),
    image_url VARCHAR(1024),
    original_image_url VARCHAR(1024),
    tags TEXT,
    notes TEXT,
    rating INTEGER NOT NULL DEFAULT 4,
    favorite BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS outfit_combos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    top_id BIGINT,
    pant_id BIGINT,
    shoe_id BIGINT,
    watch_id BIGINT,
    accessory_id BIGINT,
    jacket_id BIGINT,
    occasion VARCHAR(120),
    match_score INTEGER NOT NULL DEFAULT 0,
    ai_reason TEXT,
    saved BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_wardrobe_items_user ON wardrobe_items(user_id);
CREATE INDEX IF NOT EXISTS idx_outfit_combos_user ON outfit_combos(user_id);

CREATE TABLE IF NOT EXISTS friends_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR(255) NOT NULL,
    photo_url VARCHAR(1024),
    name VARCHAR(255) NOT NULL,
    contact_number VARCHAR(80),
    country_code VARCHAR(16),
    place VARCHAR(255),
    impact VARCHAR(32),
    lesson_learned TEXT,
    enhanced_lesson TEXT,
    tags VARCHAR(512),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_friends_logs_user ON friends_logs(user_id);

CREATE TABLE IF NOT EXISTS reels (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR(255) NOT NULL,
    platform VARCHAR(80),
    url VARCHAR(1200),
    title VARCHAR(255),
    caption TEXT,
    keywords TEXT,
    category VARCHAR(120),
    summary TEXT,
    lesson TEXT,
    action_item TEXT,
    priority VARCHAR(32),
    should_update_timetable BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_reels_user ON reels(user_id);
